can:
  channel: vcan0
  bitrate: 500000

filters:
  - can_id: 0x451
    can_mask: 0x7FE
    extended: False
  - can_id: 0x651
    can_mask: 0x7FE
    extended: False
  - can_id: 0xA00000
    can_mask: 0x1FFFFFFF
    extended: True

commands:
  lock:
      arbitrary_id: 0x451
      data: [1,4,0]
      response: "{doors} doors are LOCKED"
  unlock:
      arbitrary_id: 0x451
      data: [0,4,0]
      response: "{doors} doors are UNLOCKED"
  horn:
      arbitrary_id: 0x651
      data: [1,2,15]
      response: "Beep Beep Beep......."
